# Generated by Django 3.0.6 on 2020-06-02 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_auto_20200602_1658'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserAddressTable',
            new_name='UserAddress',
        ),
    ]
