# Generated by Django 3.0.6 on 2020-06-03 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200602_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='shipping',
            new_name='is_shipping',
        ),
    ]
