# Generated by Django 3.0.6 on 2020-06-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200528_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_receipt_link',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
