# Generated by Django 3.0.6 on 2020-06-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_receipt_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='timestamp',
            new_name='timestamp_created',
        ),
    ]
