# Generated by Django 3.0.6 on 2020-06-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_timestamp_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
