# Generated by Django 3.0.6 on 2020-05-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20200515_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
