# Generated by Django 3.0.6 on 2020-05-27 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_cartitem_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='grand_total',
        ),
    ]
