# Generated by Django 3.0.6 on 2020-06-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20200528_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total',
            new_name='sub_total',
        ),
    ]
