# Generated by Django 3.0.5 on 2020-04-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_cart_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
