# Generated by Django 3.0.5 on 2020-05-16 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerFullName', models.CharField(max_length=50)),
                ('sellerListingName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('dateAdded', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Seller'),
        ),
    ]
