# Generated by Django 3.0.5 on 2020-05-16 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20200516_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_full',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.CharField(max_length=60),
        ),
    ]
