# Generated by Django 3.0.5 on 2020-05-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20200516_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='', help_text='Select the categories you would like the product to appear in', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_full',
            field=models.TextField(default='', help_text='Your full item description when item details are viewed', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=models.CharField(default='', help_text='Limit 30 Characters: Brief product description on item card', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.CharField(help_text='Upload product image', max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity available - Default 1'),
        ),
    ]
