# Generated by Django 3.0.5 on 2020-05-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_auto_20200522_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=models.CharField(default='', help_text='Limit 30 characters: Brief product description on item card', max_length=50),
        ),
    ]
