# Generated by Django 3.0.6 on 2020-05-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20200522_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='bio_description',
            field=models.TextField(blank=True, default='', help_text='Brief bio describing who you are and what you do', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload your profile picture for our about page', null=True, upload_to='seller_profiles'),
        ),
    ]
