# Generated by Django 3.0.6 on 2020-06-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_seller_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='user',
            new_name='seller',
        ),
    ]
