# Generated by Django 3.0.6 on 2020-06-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_auto_20200629_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='bio_description',
            field=models.TextField(default='', help_text='Brief bio describing who you are and what you do', max_length=500),
        ),
    ]
