# Generated by Django 3.0.6 on 2020-07-01 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0039_auto_20200629_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='seller',
            new_name='user',
        ),
    ]
