# Generated by Django 3.0.6 on 2020-07-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0040_auto_20200701_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=models.CharField(default='', help_text='Limit 75 characters: Product description on item card', max_length=75),
        ),
    ]
