# Generated by Django 3.0.6 on 2020-07-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0042_auto_20200704_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=models.TextField(default='', help_text='Limit 100 characters: Product description on item card', max_length=100),
        ),
    ]
