# Generated by Django 3.0.6 on 2020-07-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_auto_20200704_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(help_text='There are no image size restrictions, but sqaure images will always render without any cropping.', upload_to='product_images'),
        ),
    ]
