# Generated by Django 3.0.6 on 2020-07-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_auto_20200707_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=models.TextField(default='', help_text='Limit 100 characters: Brief discription of the item', max_length=100),
        ),
    ]
