# Generated by Django 3.0.6 on 2020-07-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0049_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='subject',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
