# Generated by Django 3.0.6 on 2020-07-11 02:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_auto_20200710_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
