# Generated by Django 3.0.6 on 2020-07-11 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0051_productreview_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='product_id',
            new_name='product',
        ),
    ]
