# Generated by Django 3.0.6 on 2020-07-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_auto_20200710_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
