# Generated by Django 3.0.2 on 2020-04-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.IntegerField(blank=True, default=0, null=True)),
                ('productName', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField()),
                ('productImage', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('dateListed', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
