# Generated by Django 3.0.2 on 2020-04-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200414_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='id',
        ),
        migrations.AlterField(
            model_name='products',
            name='productID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
