# Generated by Django 3.0.2 on 2020-04-14 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200414_0259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
