# Generated by Django 3.0.5 on 2020-05-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20200516_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='dateAdded',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='sellerFullName',
            new_name='seller_full_name',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='sellerListingName',
            new_name='seller_listing_name',
        ),
    ]
