# Generated by Django 3.0.5 on 2020-05-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20200516_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='dateListed',
            new_name='date_listed',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productID',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productImage',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productName',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description_full',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_short',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
