# Generated by Django 3.0.5 on 2020-05-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20200516_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_short',
            field=models.CharField(default='', help_text='Limit 30 characters: Brief product description on item card', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(help_text='Limit 30 characters', max_length=30),
        ),
    ]
