# Generated by Django 3.0.5 on 2020-05-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20200519_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(help_text='Select the categories you would like the product to appear in', to='store.Category'),
        ),
    ]
