# Generated by Django 3.0.5 on 2020-05-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20200520_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
