# Generated by Django 3.0.6 on 2020-05-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20200526_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping cost for this item', max_digits=6),
        ),
    ]
